name: Test server 1.18.2
on:
  push:
    branches:
      - '1.18.2/*'
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  validate-gradle:
    name: "Validate Gradle wrapper"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true # Clone with vs-core submodule
      - uses: gradle/wrapper-validation-action@v1

  download:
    name: Download dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Download CBC common
        uses: Fork-on-the-Table-Collective/upload-to-download-from-gdrive@v2.0.0
        with:
          credentials: ${{ secrets.GSA_CREDENTIALS }}
          actionType: download
          localPath: ./common/jars/createbigcannons-5.5.0-dev+mc.1.20.1-fabric-build.50.jar
          googleFileId: 1Nj1TlU_PC_mZuEj6e5lCR3EwRTitOxt-

      - name: Download CBC fabric
        uses: Fork-on-the-Table-Collective/upload-to-download-from-gdrive@v2.0.0
        with:
          credentials: ${{ secrets.GSA_CREDENTIALS }}
          actionType: download
          localPath: ./fabric/jars/createbigcannons-5.5.0-dev+mc.1.20.1-fabric-build.50.jar
          googleFileId: 1Nj1TlU_PC_mZuEj6e5lCR3EwRTitOxt-

      - name: Download CBC forge
        uses: Fork-on-the-Table-Collective/upload-to-download-from-gdrive@v2.0.0
        with:
          credentials: ${{ secrets.GSA_CREDENTIALS }}
          actionType: download
          localPath: ./forge/jars/createbigcannons-5.5.0-dev+mc.1.20.1-forge-build.50.jar
          googleFileId: 1jKit9IvnzyucbGzooDP0tPWUAux6NYsl

      - name: Download Modern Warfare
        uses: Fork-on-the-Table-Collective/upload-to-download-from-gdrive@v2.0.0
        with:
          credentials: ${{ secrets.GSA_CREDENTIALS }}
          actionType: download
          localPath: ./forge/jars/cbcmodernwarfare-0.0.5b+mc.1.20.1-forge.jar
          googleFileId: 1wBoucGOURq5dkLx1IvQ_DP29uxB7iQd8

      - name: Download FTB Chunks
        uses: Fork-on-the-Table-Collective/upload-to-download-from-gdrive@v2.0.0
        with:
          credentials: ${{ secrets.GSA_CREDENTIALS }}
          actionType: download
          localPath: ./common/jars/ftb-chunks-fabric-2001.3.1.jar
          googleFileId: 1syotEGMA2svNL2vaXp35yF7fD9NyDmZp

  test-server:
    name: Test Server
    strategy:
      matrix:
        serverType: [ 'fabric', 'forge' ]
    runs-on: ubuntu-latest
    timeout-minutes: 20 # Fail after 20 minutes
    steps:
      - name: Shallow Clone (--recurse-submodules)
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Gradle & Caches
        uses: "./.github/actions/setup-gradle"

      - name: Test Server
        uses: ValkyrienSkies/Minecraft-Architectury-Testing@v1.9
        with:
          serverType: ${{ matrix.serverType }}
